// Code generated by MockGen. DO NOT EDIT.
// Source: C:/MyProjects/rest-in-memory-cache/internal/repo/repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repo "github.com/HappyFreeman/rest-in-memory-cache/internal/repo"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockRepository) CreateTask(ctx context.Context, task repo.Task, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockRepositoryMockRecorder) CreateTask(ctx, task, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockRepository)(nil).CreateTask), ctx, task, userId)
}

// DeleteTaskById mocks base method.
func (m *MockRepository) DeleteTaskById(ctx context.Context, id, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskById", ctx, id, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskById indicates an expected call of DeleteTaskById.
func (mr *MockRepositoryMockRecorder) DeleteTaskById(ctx, id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskById", reflect.TypeOf((*MockRepository)(nil).DeleteTaskById), ctx, id, userId)
}

// GetTaskById mocks base method.
func (m *MockRepository) GetTaskById(ctx context.Context, id, userId int) (repo.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskById", ctx, id, userId)
	ret0, _ := ret[0].(repo.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskById indicates an expected call of GetTaskById.
func (mr *MockRepositoryMockRecorder) GetTaskById(ctx, id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskById", reflect.TypeOf((*MockRepository)(nil).GetTaskById), ctx, id, userId)
}

// GetTasks mocks base method.
func (m *MockRepository) GetTasks(ctx context.Context, userId int) ([]repo.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, userId)
	ret0, _ := ret[0].([]repo.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockRepositoryMockRecorder) GetTasks(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockRepository)(nil).GetTasks), ctx, userId)
}

// UpdateTaskById mocks base method.
func (m *MockRepository) UpdateTaskById(ctx context.Context, id int, task repo.Task, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskById", ctx, id, task, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskById indicates an expected call of UpdateTaskById.
func (mr *MockRepositoryMockRecorder) UpdateTaskById(ctx, id, task, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskById", reflect.TypeOf((*MockRepository)(nil).UpdateTaskById), ctx, id, task, userId)
}
